<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2017 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<form id="discount-coupon-form" method="post" onsubmit="return false;">
    <div class="discount">
        <div class="discount-form">
            <label for="coupon_code"><?php echo $this->helper('checkout')->__('Discount Codes') ?></label>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <div class="field-wrapper">
                <input class="input-text" type="text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" />
                <div class="button-wrapper">
                    <button type="button" id="coupon_code_apply_button" title="<?php echo Mage::helper('core')->quoteEscape($this->helper('checkout')->__('Apply')) ?>" class="button2" onclick="APA.submitCoupon()" value="<?php echo $this->helper('checkout')->__('Apply') ?>"><span><span><?php echo $this->helper('checkout')->__('Apply') ?></span></span></button>
                    <?php if (strlen($this->getCouponCode())): ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->helper('checkout')->__('Cancel')) ?>" class="button2 cancel-coupon" onclick="APA.cancelCoupon()" value="<?php echo $this->helper('checkout')->__('Cancel') ?>"><span><span><?php echo $this->helper('checkout')->__('Cancel') ?></span></span>
                        </button>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    document.getElementById('coupon_code').addEventListener('keyup', function(event) {
        event.preventDefault();
        if (event.keyCode == 13) {
            document.getElementById('coupon_code_apply_button').click();
        }
    });
    document.getElementById('coupon_code').addEventListener('change', function(event) {
        event.preventDefault();
        var couponCode = document.getElementById('coupon_code').value;
        if (couponCode && couponCode != '<?php echo $this->getCouponCode(); ?>' && couponCode.length > 1) {
            document.getElementById('coupon_code_apply_button').click();
        }
    });
//]]>
</script>
